# src/container/vector/destination/linear/container.py

"""
Module: container.vector.destination.linear.container
Author: Banji Lawal
Created: 2026-04-03
version: 1.0.1
"""

from __future__ import annotations

from typing import Optional, Tuple, cast

from container import DestinationVectorSet
from model import Vector


class LinearDestinationSet(DestinationVectorSet):
    """
    Role:
        -   Data Holder
        
    Responsibilities:
        1.  Store root and destination vectors from a 1D space generated by
            a Stepper.

    Attributes:
        root: Vector
        entries: Optional[Tuple[Vector, ...]]
        
    Provides:

    Super Class:
        DestinationVectorSet
    """
    _root: Vector
    
    def __init__(
            self,
            root: Vector,
            entries: Optional[Tuple[Vector, ...]] | None = None
    ):
        """
        Args:
            root: Vector
            entries: Optional[Tuple[Vector, ...]]
        """
        super().__init__(root=root, entries=entries)
        
        
    def remove_root_destination(self) -> LinearDestinationSet:
        if not self.is_root_in_destinations:
            return self
        vector_set = super().remove_root_from_destinations()
        return cast(LinearDestinationSet, vector_set)
        

        