# src/space/destination/linear/space.py

"""
Module: space.destination.linear.space
Author: Banji Lawal
Created: 2026-04-03
version: 1.0.1
"""

from __future__ import annotations

from typing import Optional, cast


from model import Vector
from register import VectorRegister
from space import DestinationVectorSet


class LinearDestinationSet(DestinationVectorSet):
    """
    Role:
        -   Data Holder
        
    Responsibilities:
        1.  Store root and destination vectors from a 1D space generated by
            a Stepper.

    Attributes:
        endpoints: VectorRegister,
        destinations: Optional[VectorSet]
        
    Provides:

    Super Class:
        DestinationVectorSet
    """
    _endpoints: VectorRegister
    
    def __init__(
            self,
            endpoints: VectorRegister,
            destinations: Optional[VectorSet] | None = None,
    ):
        """
        Args:
            endpoints: VectorRegister,
            destinations: Optional[VectorSet]
        """
        super().__init__(root=endpoints.u, destinations=destinations)
        self._endpoints = endpoints
        
    @property
    def terminus(self) -> Vector:
        return self._endpoints.v
    
    @property
    def is_circle(self) -> bool:
        return self._endpoints.u_is_v
    
    @property
    def is_not_circle(self) -> bool:
        return not self.is_circle
    
    @property
    def terminus_is_destination(self) -> bool:
        return self.terminus in self.destinations
    
    @property
    def terminus_not_in_destinations(self) -> bool:
        return not self.terminus_is_destination
    
    def remove_root_from_destinations(self) -> LinearDestinationSet:
        if self.root_is_not_destination:
            return self
        return cast(LinearDestinationSet, super().remove_root_from_destinations())
    
    def add_terminus_destination(self) -> LinearDestinationSet:
        if self.terminus_is_destination:
            return self
        temp = self.destinations.to_list
        temp.append(self.terminus)
        return LinearDestinationSet(
            endpoints=self._endpoints,
            destinations=VectorSet(tuple(temp)),
            
        )
        

        